// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.0
// source: email.proto

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InboxClient is the client API for Inbox service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InboxClient interface {
	GetEmails(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error)
}

type inboxClient struct {
	cc grpc.ClientConnInterface
}

func NewInboxClient(cc grpc.ClientConnInterface) InboxClient {
	return &inboxClient{cc}
}

func (c *inboxClient) GetEmails(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error) {
	out := new(EmailResponse)
	err := c.cc.Invoke(ctx, "/Inbox/GetEmails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InboxServer is the server API for Inbox service.
// All implementations must embed UnimplementedInboxServer
// for forward compatibility
type InboxServer interface {
	GetEmails(context.Context, *EmailRequest) (*EmailResponse, error)
	mustEmbedUnimplementedInboxServer()
}

// UnimplementedInboxServer must be embedded to have forward compatible implementations.
type UnimplementedInboxServer struct {
}

func (UnimplementedInboxServer) GetEmails(context.Context, *EmailRequest) (*EmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmails not implemented")
}
func (UnimplementedInboxServer) mustEmbedUnimplementedInboxServer() {}

// UnsafeInboxServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InboxServer will
// result in compilation errors.
type UnsafeInboxServer interface {
	mustEmbedUnimplementedInboxServer()
}

func RegisterInboxServer(s grpc.ServiceRegistrar, srv InboxServer) {
	s.RegisterService(&Inbox_ServiceDesc, srv)
}

func _Inbox_GetEmails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InboxServer).GetEmails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Inbox/GetEmails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InboxServer).GetEmails(ctx, req.(*EmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Inbox_ServiceDesc is the grpc.ServiceDesc for Inbox service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Inbox_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Inbox",
	HandlerType: (*InboxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEmails",
			Handler:    _Inbox_GetEmails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "email.proto",
}
